server:
  use-forward-headers: true

management:
  context-path: /system

spring:
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: ${DOCKER_IP}
    port: 5672
    username: guest
    password: guest
  jpa:
    generate-ddl: true
    show-sql: false
  zipkin:
    baseUrl: "http://zipkin:9411"
  sleuth:
    sampler:
      percentage: 1.0
  jmx:
    enabled: false

flyway:
  enabled: false

health:
  config:
    enabled: false

logging:
  level:
    root: 'INFO'
    org.apache.tomcat.jdbc.pool: 'INFO'
    org.hibernate: 'WARN'
    org.hibernate.type.descriptor.java: 'OFF'
    org.javamoney: 'WARN'
    org.springframework.beans.factory.support: 'WARN'
    org.springframework.boot.actuate.endpoint.mvc: 'WARN'
    org.springframework.boot.web.servlet: 'WARN'
    org.springframework.context.annotation.ConfigurationClassPostProcessor: 'OFF'
    org.springframework.context.support: 'WARN'
    org.springframework.data.rest.webmvc: 'WARN'
    org.springframework.web.servlet: 'WARN'
    org.springframework.amqp.rabbit.core.RabbitAdmin: 'WARN'
